[package]
name = "sentinel"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "sentinel"

[features]
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.31.0"
